### ISSUE TITLE
Bad practice

### ISSUE THREAD

**Issue by ghost** [Hexeption/DarkForge#1]
Stop using static because you're too lazy to get the instance of a module, it's bad practice

**Comment by larsenv** [comment]
Void, what happened to your Discord?

We're trying to contact you about the rc24 domain and we're unable to.

(no one's able to access the site until you talk to us)

**Comment by ghost** [comment]
Stop stalking me, you autists told me to quit and I did

**Comment by larsenv** [comment]
We would like to have our domain back...

**Comment by ghost** [comment]
You've never paid me a cent

**Comment by larsenv** [comment]
But we could buy it off you right now?

**Comment by ghost** [comment]
I'm not looking to make any money, just wait until August when it expires. In fact I think rc24.xyz is better than riiconnect24.net. Shorter domain names look nice

**Comment by ghost** [comment]
I was busy with some family things for a while and when I wanted to try to start helping out again I was simply told to fuck off

**Comment by larsenv** [comment]
We would happily let you back in, it's just you were removed for inactivity. If you don't wish to, then sure. The only reason we request the domain back is because some services are using it and thus it requires repatching.

**Comment by ghost** [comment]
Tell your slaves to stop spamming my discord with friend requests

**Comment by larsenv** [comment]
We don't control our users.
