### ISSUE TITLE
2 question

### ISSUE THREAD

**Issue by blackandwhiteclient** [Hexeption/DarkForge#7]
1. When do you want to realse it?
2. Why don't you do a gui api, it is very good in this client.

**Comment by Voldemart** [comment]
Yeah

**Comment by Hexeption** [comment]
[Latest Version](http://teamcity.hexeption.co.uk:8111/repository/download/DarkForge_ReleaseBuild/83:id/darkforge-1.11.2-release-b19-univeral.jar) Hosted on TeamCity while github API gets fixed (login as guest)

I may at some point make it into a api
